name: AnimationLib
version: 0.1.1
main: me.captainbern.animationlib.AnimationLib
author: CaptainBern
description: A small and compact library to play diffrent animation by making use of fancy reflection.