name: AnimationLib
version: ${project.version}
main: me.captainbern.animationlib.AnimationLib
author: CaptainBern
description: A small and compact library to play different animation by making use of fancy reflection.

commands:
    animation:
        aliases: [al, ad, animdebug, animtest]
        description: Shows all possible animations and a help command.

    playeranimation:
        aliases: [pa]
        description: Command used to debug player animations.

    blockanimation:
        aliases: [ba]
        description: Command used to debug the block animations.

permissions:
    animationlib.debug.*:
        default: op
        description: Give players with op everything by default
