name: AnimationLib
version: ${project.version}
main: me.captainbern.animationlib.AnimationLib
author: CaptainBern
description: A small and compact library to play different animation by making use of fancy reflection.